@baseUrl = http://localhost:3333

# @name Create_account
POST {{baseUrl}}/accounts
 Content-Type: application/json

    {
        "name": "teste3",
        "email":"teste3terra.com.br",
        "password": "123456"
    }

###


# @name Authenticate
POST {{baseUrl}}/accounts
 Content-Type: application/json

    {
        "name": "teste3",
        "email":"teste3@terra.com.br",
        "password": "123456"
    }